<?php

/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 * Implementing hook_theme
 */
function movies_theme($existing, $type, $theme, $path) {

  return array(
    'movies' => array(
        'variables' => array('items' => array(), 'title' => '', 'genres' => array(), 'numOfPages' => 0, 'selectedGenre' => '', 'selectedFilter' => '', 'selectedPage' => '')
    )
  );
}

function movie_attachments(array &$page) {
  $page['#attached']['library'][] = 'movies/movies_css';
}


function movies_node_view(array &$build, NodeInterface $node, $display, $view_mode) {
  if ($node->getType() == 'movie' && $view_mode == 'full') {
    $build['#cache']['max-age'] = 500;
  }
}
